-------------------------------------------------------
-- PETJOURNEY TUTOR API - SEED ORACLE
-- Execute este script depois de rodar as migrations.
-- Objetivo: popular o banco com dados mínimos para testar a API.
-------------------------------------------------------

DELETE FROM TBLEMBRETE;
DELETE FROM TBPET;
DELETE FROM TBTUTOR;
DELETE FROM TBCLINICA;
DELETE FROM TBRACA;
DELETE FROM TBESPECIE;

COMMIT;

INSERT INTO TBESPECIE (NMESPECIE) VALUES ('Cachorro');
INSERT INTO TBESPECIE (NMESPECIE) VALUES ('Gato');
INSERT INTO TBESPECIE (NMESPECIE) VALUES ('Ave');
INSERT INTO TBESPECIE (NMESPECIE) VALUES ('Coelho');

INSERT INTO TBRACA (NMRACA, IDESPECIE)
VALUES ('Labrador', (SELECT IDESPECIE FROM TBESPECIE WHERE NMESPECIE = 'Cachorro'));

INSERT INTO TBRACA (NMRACA, IDESPECIE)
VALUES ('Shih Tzu', (SELECT IDESPECIE FROM TBESPECIE WHERE NMESPECIE = 'Cachorro'));

INSERT INTO TBRACA (NMRACA, IDESPECIE)
VALUES ('Persa', (SELECT IDESPECIE FROM TBESPECIE WHERE NMESPECIE = 'Gato'));

INSERT INTO TBRACA (NMRACA, IDESPECIE)
VALUES ('Siamês', (SELECT IDESPECIE FROM TBESPECIE WHERE NMESPECIE = 'Gato'));

INSERT INTO TBCLINICA
(NMCLINICA, DSENDERECO, NRTELEFONE, DSEMAIL, DSSTATUS)
VALUES
('Clinica Pet Care', 'Rua das Flores, 100 - Sao Paulo', '11999999999', 'contato@petcare.com', 'ATIVA');

INSERT INTO TBCLINICA
(NMCLINICA, DSENDERECO, NRTELEFONE, DSEMAIL, DSSTATUS)
VALUES
('Hospital Veterinario Vida Animal', 'Av Paulista, 500 - Sao Paulo', '11888888888', 'vidaanimal@email.com', 'ATIVA');

INSERT INTO TBTUTOR
(NMTUTOR, DSEMAIL, NRTELEFONE, DSPLANO, DTCADASTRO)
VALUES
('Lucas Viana', 'lucas.seed@email.com', '11977777777', 'FREE', SYSDATE);

INSERT INTO TBTUTOR
(NMTUTOR, DSEMAIL, NRTELEFONE, DSPLANO, DTCADASTRO)
VALUES
('Maria Oliveira', 'maria.seed@email.com', '11966666666', 'PREMIUM', SYSDATE);

INSERT INTO TBPET
(NMPET, DTNASCIMENTO, DSSEXO, IDTUTOR, IDESPECIE, IDRACA, IDCLINICA)
VALUES
(
    'Thor',
    DATE '2021-03-10',
    'M',
    (SELECT IDTUTOR FROM TBTUTOR WHERE DSEMAIL = 'lucas.seed@email.com'),
    (SELECT IDESPECIE FROM TBESPECIE WHERE NMESPECIE = 'Cachorro'),
    (SELECT IDRACA FROM TBRACA WHERE NMRACA = 'Labrador'),
    (SELECT IDCLINICA FROM TBCLINICA WHERE DSEMAIL = 'contato@petcare.com')
);

INSERT INTO TBPET
(NMPET, DTNASCIMENTO, DSSEXO, IDTUTOR, IDESPECIE, IDRACA, IDCLINICA)
VALUES
(
    'Luna',
    DATE '2020-07-15',
    'F',
    (SELECT IDTUTOR FROM TBTUTOR WHERE DSEMAIL = 'lucas.seed@email.com'),
    (SELECT IDESPECIE FROM TBESPECIE WHERE NMESPECIE = 'Cachorro'),
    NULL,
    NULL
);

INSERT INTO TBLEMBRETE
(IDPET, DSTIPO, DSDESCRICAO, DTLEMBRETE, DTNOTIFICADO, DSSTATUS)
VALUES
((SELECT IDPET FROM TBPET WHERE NMPET = 'Thor'), 'VACINA', 'Aplicar vacina V10', DATE '2026-05-20', NULL, 'PENDENTE');

INSERT INTO TBLEMBRETE
(IDPET, DSTIPO, DSDESCRICAO, DTLEMBRETE, DTNOTIFICADO, DSSTATUS)
VALUES
((SELECT IDPET FROM TBPET WHERE NMPET = 'Thor'), 'BANHO', 'Banho mensal', DATE '2026-05-25', NULL, 'PENDENTE');

INSERT INTO TBLEMBRETE
(IDPET, DSTIPO, DSDESCRICAO, DTLEMBRETE, DTNOTIFICADO, DSSTATUS)
VALUES
((SELECT IDPET FROM TBPET WHERE NMPET = 'Luna'), 'CONSULTA', 'Retorno veterinario', DATE '2026-06-10', NULL, 'PENDENTE');

COMMIT;

SELECT * FROM TBESPECIE;
SELECT * FROM TBRACA;
SELECT * FROM TBCLINICA;
SELECT * FROM TBTUTOR;
SELECT * FROM TBPET;
SELECT * FROM TBLEMBRETE;
