// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetJourneyTutorApi.Data;

#nullable disable

namespace PetJourneyTutorApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519014009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetJourneyTutorApi.Models.Clinic", b =>
                {
                    b.Property<int>("IdClinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDCLINICA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClinica"));

                    b.Property<string>("DsEmail")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DSEMAIL");

                    b.Property<string>("DsEndereco")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DSENDERECO");

                    b.Property<string>("DsStatus")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DSSTATUS");

                    b.Property<string>("NmClinica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NMCLINICA");

                    b.Property<string>("NrTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NRTELEFONE");

                    b.HasKey("IdClinica");

                    b.ToTable("TBCLINICA");
                });

            modelBuilder.Entity("PetJourneyTutorApi.Models.Pet", b =>
                {
                    b.Property<int>("IdPet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDPET");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPet"));

                    b.Property<string>("DsSexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("DSSEXO");

                    b.Property<DateTime?>("DtNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DTNASCIMENTO");

                    b.Property<int?>("IdClinica")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDCLINICA");

                    b.Property<int?>("IdEspecie")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDESPECIE");

                    b.Property<int?>("IdRaca")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDRACA");

                    b.Property<int>("IdTutor")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDTUTOR");

                    b.Property<string>("NmPet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NMPET");

                    b.HasKey("IdPet");

                    b.ToTable("TBPET");
                });

            modelBuilder.Entity("PetJourneyTutorApi.Models.Reminder", b =>
                {
                    b.Property<int>("IdLembrete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDLEMBRETE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLembrete"));

                    b.Property<string>("DsDescricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DSDESCRICAO");

                    b.Property<string>("DsStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("PENDENTE")
                        .HasColumnName("DSSTATUS");

                    b.Property<string>("DsTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DSTIPO");

                    b.Property<DateTime>("DtLembrete")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DTLEMBRETE");

                    b.Property<DateTime?>("DtNotificado")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DTNOTIFICADO");

                    b.Property<int>("IdPet")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDPET");

                    b.HasKey("IdLembrete");

                    b.ToTable("TBLEMBRETE");
                });

            modelBuilder.Entity("PetJourneyTutorApi.Models.Tutor", b =>
                {
                    b.Property<int>("IdTutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDTUTOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTutor"));

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DSEMAIL");

                    b.Property<string>("DsPlano")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("FREE")
                        .HasColumnName("DSPLANO");

                    b.Property<DateTime>("DtCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DTCADASTRO")
                        .HasDefaultValueSql("SYSDATE");

                    b.Property<string>("NmTutor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NMTUTOR");

                    b.Property<string>("NrTelefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NRTELEFONE");

                    b.HasKey("IdTutor");

                    b.HasIndex("DsEmail")
                        .IsUnique();

                    b.ToTable("TBTUTOR");
                });
#pragma warning restore 612, 618
        }
    }
}
